### ISSUE TITLE
Startlette client no longer works with httpx 0.8.0

### ISSUE THREAD

**Issue by jorgecarleitao** [lepture/authlib#173]
**Describe the bug**

With httpx==0.7.8, the example https://github.com/authlib/demo-oauth-client/tree/master/starlette-google-login runs as is. However, with httpx==0.8.0, it does not.

**Error Stacks**

```
ImportError: cannot import name 'AsyncClient' from 'httpx' (/.../venv/lib/python3.7/site-packages/httpx/__init__.py)
```

**To Reproduce**

Run the example code with the latest httpx, httpx==0.8.0.

**Expected behavior**

**Environment:**

 - OS: MacOs
 - Python Version: 3.7
 - Authlib Version: 0.13

**Additional context**

**Comment by lepture** [comment]
duplicated with https://github.com/lepture/authlib/issues/171

Caused by https://github.com/encode/httpx/issues/522

**Comment by tomchristie** [comment]
My apologies. We've had a big pain point here with needing to change our approach to how we tackle sync+async support.

Until we're at 1.0 I'd recommend pinning to each median point release, to ensure you don't get hit by API changes. (Eg. pin to 0.7.x, or 0.8.x, ...)

**Comment by jorgecarleitao** [comment]
My apologies for not checking for duplicates first. @tomchristie , no worries. We all understand the 0.X.Y spirit. That is a good idea. fastAPI did it for pydantic until recently.
